produtos_static = [{'id': '623449734',
  'nome': 'ALCATRA COM QUEIJO',
  'codigo': 'ALCAQP',
  'unidade': 'kg',
  'estoque_minimo': 8.62,
  'slug': 'Alcatra',
  'marca': 'Porcão',
  'estoque': 8.34,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449795',
  'nome': 'ALMÔNDEGA BACON',
  'codigo': 'ALMOBARB',
  'unidade': 'kg',
  'estoque_minimo': 5.0,
  'slug': 'Almôndega',
  'marca': 'Recheados Brasil',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449782',
  'nome': 'ALMÔNDEGA QUEIJO',
  'codigo': 'ALMOQRB',
  'unidade': 'kg',
  'estoque_minimo': 4.5,
  'slug': 'Almôndega',
  'marca': 'Recheados Brasil',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '778208483',
  'nome': 'ANCHO ALIMENTAR',
  'codigo': 'ANCHALI',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Ancho',
  'marca': 'Alimentar',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '646749750',
  'nome': 'ANCHO DI PRIMA',
  'codigo': 'ANCHDIPDI',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Ancho',
  'marca': 'Di Prima',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '729652533',
  'nome': 'ANCHO MINERVA',
  'codigo': 'ANCHMINERV',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Ancho',
  'marca': 'Minerva',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '638403161',
  'nome': 'ANCHO MONTANA STEAKHOUSE',
  'codigo': 'ANCHMOSTKMA',
  'unidade': 'kg',
  'estoque_minimo': 4.0,
  'slug': 'Ancho',
  'marca': 'Montana Steakhouse',
  'estoque': 14.73,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449824',
  'nome': 'ASINHA RECHEADA',
  'codigo': 'ASARECHRB',
  'unidade': 'un',
  'estoque_minimo': 5.0,
  'slug': 'Asinha',
  'marca': 'Recheados Brasil',
  'estoque': 6,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449837',
  'nome': 'ASSADO DE TIRAS ARG',
  'codigo': 'ASSTIRARG',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Assado',
  'marca': 'ARG',
  'estoque': 3.15,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '661843960',
  'nome': 'BACON FATIADO',
  'codigo': 'BACNFATDNT',
  'unidade': 'un',
  'estoque_minimo': 2.0,
  'slug': 'Bacon',
  'marca': '',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '649329262',
  'nome': 'BUTCHER STEAK PORCAO',
  'codigo': 'BUTCHPORC',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Butcher',
  'marca': 'Porcão',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '733149637',
  'nome': 'CARPACCIO CARA PRETA',
  'codigo': 'CARPACCP',
  'unidade': 'un',
  'estoque_minimo': 0.0,
  'slug': 'Carpaccio',
  'marca': 'Cara Preta',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '659216777',
  'nome': 'CARRÉ CORDEIRO 1953',
  'codigo': 'CARREPLE',
  'unidade': 'kg',
  'estoque_minimo': 1.0,
  'slug': 'Carré Cordeiro',
  'marca': '1953',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449886',
  'nome': 'CHORIZO ESTÂNCIA 92',
  'codigo': 'CHRZEST92',
  'unidade': 'kg',
  'estoque_minimo': 4.0,
  'slug': 'Chorizo',
  'marca': 'Estância 92',
  'estoque': 9.97,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449902',
  'nome': 'CORAÇÃO',
  'codigo': 'CORAGAT',
  'unidade': 'kg',
  'estoque_minimo': 6.0,
  'slug': 'Coração',
  'marca': 'Jerônimos',
  'estoque': 4.5,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '692081848',
  'nome': 'COSTELINHA DIA A DIA',
  'codigo': 'COSTDIADIA',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Costelinha',
  'marca': 'Dia a Dia',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449926',
  'nome': 'COSTELINHA SUÍNA BBQ',
  'codigo': 'COSTBBQRB',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Costelinha',
  'marca': 'Recheados Brasil',
  'estoque': 5,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '706381781',
  'nome': 'COWBOY CARA PRETA',
  'codigo': 'COWBCP',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Cowboy',
  'marca': 'Cara Preta',
  'estoque': 0.64,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449932',
  'nome': 'COXINHA DA ASA',
  'codigo': 'COXINGAT',
  'unidade': 'kg',
  'estoque_minimo': 6.0,
  'slug': 'Coxinha',
  'marca': 'Jerônimos',
  'estoque': 16,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449946',
  'nome': 'DENVER CARA PRETA',
  'codigo': 'DENVCP',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Denver',
  'marca': 'Cara Preta',
  'estoque': 3.9,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '794828451',
  'nome': 'FRALDA MINERVA',
  'codigo': 'FRALDMINE',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Fralda',
  'marca': 'Minerva',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '773934587',
  'nome': 'FRALDÃO BURG',
  'codigo': 'FRALDBG',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Falda',
  'marca': 'Burg',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '770209199',
  'nome': 'FRALDÃO URUGUAIO ESTER',
  'codigo': 'FRLDURUESTR',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Fralda',
  'marca': 'Ester de Lima',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '778208038',
  'nome': 'FRALDINHA ALIMENTAR',
  'codigo': 'FRALDALI',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Fraldinha',
  'marca': 'Alimentar',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '791977192',
  'nome': 'FRALDINHA BASSI',
  'codigo': 'FRALDBASS',
  'unidade': 'kg',
  'estoque_minimo': 5.0,
  'slug': 'Fraldinha',
  'marca': 'Bassi',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '663063892',
  'nome': 'FRALDINHA CARA PRETA',
  'codigo': 'FRALDCP',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Fraldinha',
  'marca': 'Cara Preta',
  'estoque': 0.86,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449970',
  'nome': 'FRALDINHA ESTÂNCIA 92',
  'codigo': 'FRALDIEST92',
  'unidade': 'kg',
  'estoque_minimo': 5.0,
  'slug': 'Fraldinha',
  'marca': 'Estância 92',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '744114547',
  'nome': 'FRALDINHA LS',
  'codigo': 'FRALDLS',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Fraldinha',
  'marca': 'Walls',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '767806291',
  'nome': 'FRALDINHA MATABOI',
  'codigo': 'FRALDMTBOI',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Fraldinha',
  'marca': 'Mataboi',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '799895288',
  'nome': 'FRALDINHA MINERVA',
  'codigo': 'FRALDMNRVA',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Fraldinha',
  'marca': 'Minerva',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '664322273',
  'nome': 'FRALDINHA MONTANA STEAKHOUSE',
  'codigo': 'FRALDMONTANA',
  'unidade': 'kg',
  'estoque_minimo': 4.0,
  'slug': 'Fraldinha',
  'marca': 'Montana Steakhouse',
  'estoque': 5.49,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '638432052',
  'nome': 'FRALDINHA RED RARO',
  'codigo': 'FRDIRERARO',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Fraldinha',
  'marca': 'Raro',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623449997',
  'nome': 'HAMBURGUER CARA PRETA',
  'codigo': 'HAMBCP',
  'unidade': 'un',
  'estoque_minimo': 2.0,
  'slug': 'Hamburguer',
  'marca': 'Cara Preta',
  'estoque': 5,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '789712012',
  'nome': 'HAMBURGUER DE TILÁPIA',
  'codigo': 'HBRGTILP',
  'unidade': 'un',
  'estoque_minimo': 0.0,
  'slug': 'Hamburguer',
  'marca': '',
  'estoque': 16,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450013',
  'nome': 'KAFTA CHEDDAR',
  'codigo': 'KAFTCHED',
  'unidade': 'un',
  'estoque_minimo': 4.0,
  'slug': 'Kafta',
  'marca': 'Espetinhos Diferentes',
  'estoque': 5,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '649329268',
  'nome': 'LINGUIÇA  DE PERNIL PORCÃO',
  'codigo': 'LINGPERPRC',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Linguiça',
  'marca': 'Porcão',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '785293008',
  'nome': 'LINGUIÇA ARTESANAL DE TILÁPIA',
  'codigo': 'LINGARTTLP',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Linguiça',
  'marca': '',
  'estoque': 14.5,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450189',
  'nome': 'LINGUIÇA CASEIRA BRAZAS BACON',
  'codigo': 'LINGBRAZBAC',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Linguiça',
  'marca': 'Brazas',
  'estoque': 2,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450199',
  'nome': 'LINGUIÇA CASEIRA BRAZAS BACON, QUEIJO E ALHO PORÓ',
  'codigo': 'LINGBRZBQA',
  'unidade': 'kg',
  'estoque_minimo': 10.0,
  'slug': 'Linguiça',
  'marca': 'Brazas',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '800868965',
  'nome': 'LINGUIÇA CASEIRA BRAZAS FRANGO',
  'codigo': 'LINGBRZSFRG',
  'unidade': 'un',
  'estoque_minimo': 0.0,
  'slug': 'Linguiça',
  'marca': 'Brazas',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450046',
  'nome': 'LINGUIÇA CASEIRA BRAZAS PIMENTA',
  'codigo': 'LINGBRAZPIM',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Linguiça',
  'marca': 'Brazas',
  'estoque': 2.5,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450182',
  'nome': 'LINGUIÇA CASEIRA BRAZAS PIMENTA BIQUINHO',
  'codigo': 'LINGBRAZPIMBIQ',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Linguiça',
  'marca': 'Brazas',
  'estoque': 3,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450205',
  'nome': 'LINGUIÇA CASEIRA BRAZAS PROVOLONE',
  'codigo': 'LINGBRAZPRVL',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Linguiça',
  'marca': 'Brazas',
  'estoque': 3,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450210',
  'nome': 'LINGUIÇA CASEIRA BRAZAS TRADICIONAL',
  'codigo': 'LINGBRAZTRAD',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Linguiça',
  'marca': 'Brazas',
  'estoque': 4,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450220',
  'nome': 'LINGUIÇA CUIABANA',
  'codigo': 'LINGCUIABO',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Linguiça',
  'marca': 'Boníssima',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '682500784',
  'nome': 'LINGUIÇA DE CORDEIRO ARG',
  'codigo': 'LINGCORDARG',
  'unidade': 'kg',
  'estoque_minimo': 4.0,
  'slug': 'Linguiça',
  'marca': 'ARG',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450215',
  'nome': 'LINGUIÇA DE COSTELA CARA PRETA',
  'codigo': 'LINGCOSCP',
  'unidade': 'kg',
  'estoque_minimo': 6.0,
  'slug': 'Linguiça',
  'marca': 'Cara Preta',
  'estoque': 8.1,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '804981063',
  'nome': 'LINGUIÇA DE PERNIL GARAPA',
  'codigo': 'LINGPERNGARA',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Linguiça',
  'marca': '',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '794827835',
  'nome': 'MAMINHA MINERVA',
  'codigo': 'MAMIMINE',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Maminha',
  'marca': 'Minerva',
  'estoque': 1.41,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '653960156',
  'nome': 'MAMINHA STEAK MARINADO',
  'codigo': 'MAMSTKPORC',
  'unidade': 'kg',
  'estoque_minimo': 4.0,
  'slug': 'Maminha',
  'marca': '',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '634824164',
  'nome': 'MANTA SUÍNA BACON E CHEDDAR',
  'codigo': 'MANTSUINCHED',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Manta Suína',
  'marca': 'Boníssima',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450225',
  'nome': 'MANTA SUÍNA QUEIJO COALHO',
  'codigo': 'MANTSUINQC',
  'unidade': 'kg',
  'estoque_minimo': 4.0,
  'slug': 'Manta Suína',
  'marca': 'Boníssima',
  'estoque': 2.5,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450236',
  'nome': 'MEDALHÃO DE BATATA COM CHEDDAR',
  'codigo': 'MEDBATCHED',
  'unidade': 'un',
  'estoque_minimo': 5.0,
  'slug': 'Medalhão',
  'marca': 'Espetinhos Diferentes',
  'estoque': 3,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '628882233',
  'nome': 'MEDALHÃO SUINO',
  'codigo': 'MEDSURB',
  'unidade': 'un',
  'estoque_minimo': 3.0,
  'slug': 'Medalhão',
  'marca': 'Recheados Brasil',
  'estoque': {'id': '628882233',
   'nome': 'MEDALHÃO SUINO',
   'codigo': 'MEDSURB',
   'unidade': 'Pct',
   'saldo': 0,
   'depositos': [{'deposito': {'nome': 'Geral',
      'desconsiderar': 'N',
      'saldo': 0,
      'empresa': 'Brazas'}}]},
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '804677691',
  'nome': 'PÃO DE FRANGO COM REQUEIJAO',
  'codigo': 'PDFDNBT',
  'unidade': 'un',
  'estoque_minimo': 0.0,
  'slug': 'Pão de frango',
  'marca': '',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '786903341',
  'nome': 'PICANHA ALIMENTAR',
  'codigo': 'PICAALIM',
  'unidade': 'kg',
  'estoque_minimo': 5.0,
  'slug': 'Picanha',
  'marca': 'Alimentar',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '638379143',
  'nome': 'PICANHA ANA PAULA BLACK ANGUS',
  'codigo': 'PICANBLKAMI',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Picanha',
  'marca': 'Angus',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450327',
  'nome': 'PICANHA ARREBEEF',
  'codigo': 'PICARREB',
  'unidade': 'kg',
  'estoque_minimo': 1.0,
  'slug': 'Picanha',
  'marca': 'Arrebeef',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '766299129',
  'nome': 'PICANHA ARROBA',
  'codigo': 'PICARRBA',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Arroba',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450340',
  'nome': 'PICANHA BASSI',
  'codigo': 'PICBASSI',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Picanha',
  'marca': 'Bassi',
  'estoque': 7.26,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '630551037',
  'nome': 'PICANHA BRAZAS',
  'codigo': 'PICBRAZ',
  'unidade': 'kg',
  'estoque_minimo': 7.0,
  'slug': 'Picanha',
  'marca': 'Brazas',
  'estoque': 7.73,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450354',
  'nome': 'PICANHA CARA PRETA',
  'codigo': 'PICCP',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Picanha',
  'marca': 'Cara Preta',
  'estoque': 7.82,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '737002822',
  'nome': 'PICANHA CONCARSA',
  'codigo': 'PICCONCARSA',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Concarsa',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '774269426',
  'nome': 'PICANHA CRUZEIRO DO SUL',
  'codigo': 'PICCRSUL',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Cruzeiro do Sul',
  'estoque': 10.38,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450374',
  'nome': 'PICANHA DI PRIMA',
  'codigo': 'PICADIPRI',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Di Prima',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '733415440',
  'nome': 'PICANHA FINEXCOR',
  'codigo': 'PICFINEXIMP',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Finexcor',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '637005194',
  'nome': 'PICANHA FRIGOCHACO',
  'codigo': 'PICFRIGOIMP',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Picanha',
  'marca': 'Frigochaco',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '795400098',
  'nome': 'PICANHA FRIGOMERC',
  'codigo': 'PICAFRIGO',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Frigomerc',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '777807737',
  'nome': 'PICANHA FRIPAI',
  'codigo': 'PICFRPA',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Fripai',
  'estoque': 1.33,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '626302922',
  'nome': 'PICANHA GORINA',
  'codigo': 'PICAGORI',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Gorina',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '723855204',
  'nome': 'PICANHA GUARANI',
  'codigo': 'PICGUARANI',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Guarani',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450496',
  'nome': 'PICANHA MATABOI',
  'codigo': 'PICAMATBOI',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Mataboi',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '794829708',
  'nome': 'PICANHA MINERVA',
  'codigo': 'PICAMINE',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Minerva',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '801868011',
  'nome': 'PICANHA PARAGUAIA',
  'codigo': 'PICPARAG',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Paraguaia',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '768983512',
  'nome': 'PICANHA PUL B',
  'codigo': 'PICPUB',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Pul B',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450527',
  'nome': 'PICANHA PULL A',
  'codigo': 'PICAPULLA',
  'unidade': 'kg',
  'estoque_minimo': 10.0,
  'slug': 'Picanha',
  'marca': 'Pull A',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '797788298',
  'nome': 'PICANHA SANTA GIULIA',
  'codigo': 'PICSTGIU',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Santa Giulia',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '778208806',
  'nome': 'PICANHA SUINA ALIMENTAR',
  'codigo': 'PICSUIALI',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Alimentar',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450540',
  'nome': 'PICANHA SUÍNA CIA CARNE',
  'codigo': 'PICSUICIAC',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Cia Carne',
  'estoque': 2.94,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '643787433',
  'nome': 'PICANHA SUINA MELLORE',
  'codigo': 'PICSUIMEL',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Mellore',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '769851535',
  'nome': 'PICANHA SUÍNA SAUDALI',
  'codigo': 'PICSUISDL',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Saudali',
  'estoque': 15.74,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450553',
  'nome': 'PICANHA SUÍNA SCHROEDER',
  'codigo': 'PICSUISCHR',
  'unidade': 'kg',
  'estoque_minimo': 5.0,
  'slug': 'Picanha',
  'marca': 'Schroeder',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '777808809',
  'nome': 'PICANHA SUÍNA TEMPERATA',
  'codigo': 'PICSTEMP',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Picanha',
  'marca': 'Temperatta',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450568',
  'nome': 'PICANHA TACUAREMBÓ',
  'codigo': 'PICTACUA',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Picanha',
  'marca': 'Tacuarembó',
  'estoque': 1.14,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '687343884',
  'nome': 'PICOLÉ MINEIRO BBQ',
  'codigo': 'PCLMINRBBBQ',
  'unidade': 'un',
  'estoque_minimo': 4.0,
  'slug': 'Picolé Mineiro',
  'marca': '',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '687345363',
  'nome': 'PICOLÉ MINEIRO ERVAS FINAS',
  'codigo': 'PCLMINRBEF',
  'unidade': 'un',
  'estoque_minimo': 4.0,
  'slug': 'Picolé Mineiro',
  'marca': '',
  'estoque': 11,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450585',
  'nome': 'PORCHETTA',
  'codigo': 'PORCHRB',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Porchetta',
  'marca': 'Recheados Brasil',
  'estoque': 4,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '687338443',
  'nome': 'PORTERHOUSE CARA PRETA',
  'codigo': 'PORTHOUSCP',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Porterhouse',
  'marca': 'Cara Preta',
  'estoque': 5.91,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '647280665',
  'nome': 'PRIME RIB RARO',
  'codigo': 'PRMRIBRARO',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Prime Rib',
  'marca': 'Raro',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450611',
  'nome': 'SALSICHÃO',
  'codigo': 'SALSIGAT',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Salsichão',
  'marca': 'Jerônimos',
  'estoque': 9,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450624',
  'nome': 'SALSICHÃO COM QUEIJO',
  'codigo': 'SALSIQUESCHR',
  'unidade': 'un',
  'estoque_minimo': 10.0,
  'slug': 'Salsichão',
  'marca': 'Schroeder',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450740',
  'nome': 'SHORT RIB ARG',
  'codigo': 'SHRTARG',
  'unidade': 'kg',
  'estoque_minimo': 5.0,
  'slug': 'Short Rib',
  'marca': 'ARG',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450753',
  'nome': 'SHORT RIB CARA PRETA',
  'codigo': 'SHRTCP',
  'unidade': 'kg',
  'estoque_minimo': 3.0,
  'slug': 'Short Rib',
  'marca': 'Cara Preta',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '640758281',
  'nome': 'SHORT RIB RARO',
  'codigo': 'SHRTRIBRARO',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Short Rib',
  'marca': 'Raro',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623450765',
  'nome': 'SOBRECOXA DESOSSADA NA CERVEJA',
  'codigo': 'SOBREGAT',
  'unidade': 'kg',
  'estoque_minimo': 12.0,
  'slug': 'Sobrecoxa Desossada',
  'marca': 'Jerônimos',
  'estoque': 7,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '626670053',
  'nome': 'SOBRECOXA DESOSSADA PORCÃO',
  'codigo': 'SOBRPRC',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Sobrecoxa Desossada',
  'marca': 'Porcão',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '692082492',
  'nome': 'STEAK DE LOMBO',
  'codigo': 'STKLOMBDIA',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'Steak',
  'marca': '',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '623585662',
  'nome': 'T-BONE CARA PRETA',
  'codigo': 'TBONECP',
  'unidade': 'kg',
  'estoque_minimo': 2.0,
  'slug': 'T-Bone',
  'marca': 'Cara Preta',
  'estoque': 2.22,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '638867885',
  'nome': 'T-BONE MINERVA ANGUS',
  'codigo': 'TBONMINE',
  'unidade': 'kg',
  'estoque_minimo': 5.0,
  'slug': 'T-Bone',
  'marca': 'Angus',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '640758272',
  'nome': 'T-BONE RARO',
  'codigo': 'TBNERARO',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'T-Bone',
  'marca': 'Raro',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '647280670',
  'nome': 'TOMAHAWK RARO',
  'codigo': 'TOMARARO',
  'unidade': 'kg',
  'estoque_minimo': 0.0,
  'slug': 'Tomahawk',
  'marca': 'Raro',
  'estoque': 0,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0},
 {'id': '769175229',
  'nome': 'TULIPA',
  'codigo': 'TLPA',
  'unidade': 'un',
  'estoque_minimo': 0.0,
  'slug': 'Tulipa',
  'marca': 'Jerônimos',
  'estoque': 14,
  'cotacao': 0,
  'quantidade': 0,
  'disponivel': False,
  'valorfinal': 0}]