produtos_static = [{'codigo': 'ANCHMINERV',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 729652533,
  'marca': 'Minerva',
  'nome': 'ANCHO MINERVA',
  'quantidade': 4,
  'slug': 'Ancho',
  'unidade': 'kg'},
 {'codigo': 'ANCHMOSTKMA',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 14.73,
  'estoque_minimo': 4,
  'id': 638403161,
  'marca': 'Montana Steakhouse',
  'nome': 'ANCHO MONTANA STEAKHOUSE',
  'quantidade': 4,
  'slug': 'Ancho',
  'unidade': 'kg'},
 {'codigo': 'ASARECHRB',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 6.0,
  'estoque_minimo': 5,
  'id': 623449824,
  'marca': 'Recheados Brasil',
  'nome': 'ASINHA RECHEADA',
  'quantidade': 4,
  'slug': 'Asinha',
  'unidade': 'un'},
 {'codigo': 'ASSTIRARG',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 3.15,
  'estoque_minimo': 2,
  'id': 623449837,
  'marca': 'ARG',
  'nome': 'ASSADO DE TIRAS ARG',
  'quantidade': 4,
  'slug': 'Assado',
  'unidade': 'kg'},
 {'codigo': 'BACNFATDNT',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 2,
  'id': 661843960,
  'marca': '',
  'nome': 'BACON FATIADO',
  'quantidade': 4,
  'slug': 'Bacon',
  'unidade': 'un'},
 {'codigo': 'BUTCHPORC',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 649329262,
  'marca': 'Porcão',
  'nome': 'BUTCHER STEAK PORCAO',
  'quantidade': 4,
  'slug': 'Butcher',
  'unidade': 'kg'},
 {'codigo': 'CARPACCP',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 733149637,
  'marca': 'Cara Preta',
  'nome': 'CARPACCIO CARA PRETA',
  'quantidade': 4,
  'slug': 'Carpaccio',
  'unidade': 'un'},
 {'codigo': 'CARREPLE',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 1,
  'id': 659216777,
  'marca': '1953',
  'nome': 'CARRÉ CORDEIRO 1953',
  'quantidade': 4,
  'slug': 'Carré Cordeiro',
  'unidade': 'kg'},
 {'codigo': 'CHRZEST92',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 9.97,
  'estoque_minimo': 4,
  'id': 623449886,
  'marca': 'Estância 92',
  'nome': 'CHORIZO ESTÂNCIA 92',
  'quantidade': 4,
  'slug': 'Chorizo',
  'unidade': 'kg'},
 {'codigo': 'CORAGAT',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 4.5,
  'estoque_minimo': 6,
  'id': 623449902,
  'marca': 'Jerônimos',
  'nome': 'CORAÇÃO',
  'quantidade': 4,
  'slug': 'Coração',
  'unidade': 'kg'},
 {'codigo': 'COSTDIADIA',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 2,
  'id': 692081848,
  'marca': 'Dia a Dia',
  'nome': 'COSTELINHA DIA A DIA',
  'quantidade': 4,
  'slug': 'Costelinha',
  'unidade': 'kg'},
 {'codigo': 'COSTBBQRB',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 5.0,
  'estoque_minimo': 3,
  'id': 623449926,
  'marca': 'Recheados Brasil',
  'nome': 'COSTELINHA SUÍNA BBQ',
  'quantidade': 4,
  'slug': 'Costelinha',
  'unidade': 'kg'},
 {'codigo': 'COWBCP',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.64,
  'estoque_minimo': 0,
  'id': 706381781,
  'marca': 'Cara Preta',
  'nome': 'COWBOY CARA PRETA',
  'quantidade': 4,
  'slug': 'Cowboy',
  'unidade': 'kg'},
 {'codigo': 'COXINGAT',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 16.0,
  'estoque_minimo': 6,
  'id': 623449932,
  'marca': 'Jerônimos',
  'nome': 'COXINHA DA ASA',
  'quantidade': 4,
  'slug': 'Coxinha',
  'unidade': 'kg'},
 {'codigo': 'DENVCP',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 3.9,
  'estoque_minimo': 2,
  'id': 623449946,
  'marca': 'Cara Preta',
  'nome': 'DENVER CARA PRETA',
  'quantidade': 4,
  'slug': 'Denver',
  'unidade': 'kg'},
 {'codigo': 'FRALDMINE',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 794828451,
  'marca': 'Minerva',
  'nome': 'FRALDA MINERVA',
  'quantidade': 4,
  'slug': 'Fralda',
  'unidade': 'kg'},
 {'codigo': 'FRALDBG',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 773934587,
  'marca': 'Burg',
  'nome': 'FRALDÃO BURG',
  'quantidade': 4,
  'slug': 'Falda',
  'unidade': 'kg'},
 {'codigo': 'FRLDURUESTR',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 770209199,
  'marca': 'Ester de Lima',
  'nome': 'FRALDÃO URUGUAIO ESTER',
  'quantidade': 4,
  'slug': 'Fralda',
  'unidade': 'kg'},
 {'codigo': 'FRALDALI',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 778208038,
  'marca': 'Alimentar',
  'nome': 'FRALDINHA ALIMENTAR',
  'quantidade': 4,
  'slug': 'Fraldinha',
  'unidade': 'kg'},
 {'codigo': 'FRALDBASS',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 5,
  'id': 791977192,
  'marca': 'Bassi',
  'nome': 'FRALDINHA BASSI',
  'quantidade': 4,
  'slug': 'Fraldinha',
  'unidade': 'kg'},
 {'codigo': 'FRALDCP',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.86,
  'estoque_minimo': 2,
  'id': 663063892,
  'marca': 'Cara Preta',
  'nome': 'FRALDINHA CARA PRETA',
  'quantidade': 4,
  'slug': 'Fraldinha',
  'unidade': 'kg'},
 {'codigo': 'FRALDIEST92',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 5,
  'id': 623449970,
  'marca': 'Estância 92',
  'nome': 'FRALDINHA ESTÂNCIA 92',
  'quantidade': 4,
  'slug': 'Fraldinha',
  'unidade': 'kg'},
 {'codigo': 'FRALDLS',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 744114547,
  'marca': 'Walls',
  'nome': 'FRALDINHA LS',
  'quantidade': 4,
  'slug': 'Fraldinha',
  'unidade': 'kg'},
 {'codigo': 'FRALDMTBOI',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 767806291,
  'marca': 'Mataboi',
  'nome': 'FRALDINHA MATABOI',
  'quantidade': 4,
  'slug': 'Fraldinha',
  'unidade': 'kg'},
 {'codigo': 'FRALDMNRVA',
  'cotacao': 14.52,
  'disponivel': False,
  'estoque': 0.0,
  'estoque_minimo': 0,
  'id': 799895288,
  'marca': 'Minerva',
  'nome': 'FRALDINHA MINERVA',
  'quantidade': 4,
  'slug': 'Fraldinha',
  'unidade': 'kg'}]