<template>
  <div>
    <Estoque
      class="card"
      :produtos="this.produtos"
      :loading="this.loading"
      :barra="this.barra"
    />
    <Ranking
      class="card"
      :produtos="this.produtos"
      :slug="this.slug"
      :fornecedores="this.fornecedores"
    />
  </div>
</template>

<script>
import Vue from "vue";
import Estoque from "../components/Estoque/GridEstoque.vue";
import Ranking from "../components/Ranking/RankingPage.vue";

export default Vue.extend({
  name: "MainPage",

  components: {
    Estoque,
    Ranking,
  },
  data: function () {
    return {
      produtos: [],
      apiUrl: "https://628b088d667aea3a3e25f63a.mockapi.io/produtos",
      loading: "",
      barra: true,
      slug: [],
      fornecedores: [],
    };
  },
  created: function () {
    this.requestEstoque();
  },
  methods: {
    requestEstoque() {
      this.loading = "waiting";
      let apiResponse;

      fetch(this.apiUrl)
        .then(async (response) => {
          apiResponse = await response.json();

          if (!response.ok) {
            this.loading = "error";
            const error =
              (apiResponse && apiResponse.message) || response.statusText;
            return Promise.reject(error);
          }

          this.loading = "success";

          // this.produtos = apiResponse.map((produto) => {
          // if(produto.estoque < produto.estoque_minimo){
          //   produto.situacao = "Abaixo do estoque"
          // } else if(produto.estoque > produto.estoque_minimo){
          //   produto.situacao = `Acima do estoque em ${parseFloat(item.estoque - item.estoque_minimo).toFixed(2)} ${item.unidade}`
          // } else {
          //   produto.situacao = "Neutro"
          // }
          //   produto.estoque += ' ' + produto.unidade
          //   produto.estoque_minimo += ' ' + produto.unidade
          //   if(produto.marca == ''){
          //     produto.marca = 'Fornecedor nao disponivel'
          //   }
          //   this.slug.unshift(produto.slug)
          //   this.fornecedores.unshift(produto.marca)
          //   return produto;
          // });
          this.produtos = [
            {
              codigo: "ALCAQP",
              estoque: 10.25,
              estoque_minimo: 8.62,
              id: "623449734",
              marca: "Porcão",
              nome: "ALCATRA COM QUEIJO",
              slug: "Alcatra",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "ALMOBARB",
              estoque: 0,
              estoque_minimo: 5.0,
              id: "623449795",
              marca: "Recheados Brasil",
              nome: "ALMÔNDEGA BACON",
              slug: "Almôndega",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "ALMOQRB",
              estoque: 0,
              estoque_minimo: 4.5,
              id: "623449782",
              marca: "Recheados Brasil",
              nome: "ALMÔNDEGA QUEIJO",
              slug: "Almôndega",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "ANCHALI",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "778208483",
              marca: "Alimentar",
              nome: "ANCHO ALIMENTAR",
              slug: "Ancho",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "ANCHDIPDI",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "646749750",
              marca: "Di Prima",
              nome: "ANCHO DI PRIMA",
              slug: "Ancho",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "ANCHMINERV",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "729652533",
              marca: "Minerva",
              nome: "ANCHO MINERVA",
              slug: "Ancho",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "ANCHMOSTKMA",
              estoque: 14.73,
              estoque_minimo: 4.0,
              id: "638403161",
              marca: "Montana Steakhouse",
              nome: "ANCHO MONTANA STEAKHOUSE",
              slug: "Ancho",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "ASARECHRB",
              estoque: 7,
              estoque_minimo: 5.0,
              id: "623449824",
              marca: "Recheados Brasil",
              nome: "ASINHA RECHEADA",
              slug: "Asinha",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "ASSTIRARG",
              estoque: 3.15,
              estoque_minimo: 2.0,
              id: "623449837",
              marca: "ARG",
              nome: "ASSADO DE TIRAS ARG",
              slug: "Assado",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "BACNFATDNT",
              estoque: 0,
              estoque_minimo: 2.0,
              id: "661843960",
              marca: "",
              nome: "BACON FATIADO",
              slug: "Bacon",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "BUTCHPORC",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "649329262",
              marca: "Porcão",
              nome: "BUTCHER STEAK PORCAO",
              slug: "Butcher",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "CARPACCP",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "733149637",
              marca: "Cara Preta",
              nome: "CARPACCIO CARA PRETA",
              slug: "Carpaccio",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "CARREPLE",
              estoque: 0,
              estoque_minimo: 1.0,
              id: "659216777",
              marca: "1953",
              nome: "CARRÉ CORDEIRO 1953",
              slug: "Carré Cordeiro",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "CHRZEST92",
              estoque: 9.97,
              estoque_minimo: 4.0,
              id: "623449886",
              marca: "Estância 92",
              nome: "CHORIZO ESTÂNCIA 92",
              slug: "Chorizo",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "CORAGAT",
              estoque: 5,
              estoque_minimo: 6.0,
              id: "623449902",
              marca: "Jerônimos",
              nome: "CORAÇÃO",
              slug: "Coração",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "COSTDIADIA",
              estoque: 0,
              estoque_minimo: 2.0,
              id: "692081848",
              marca: "Dia a Dia",
              nome: "COSTELINHA DIA A DIA",
              slug: "Costelinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "COSTBBQRB",
              estoque: 5,
              estoque_minimo: 3.0,
              id: "623449926",
              marca: "Recheados Brasil",
              nome: "COSTELINHA SUÍNA BBQ",
              slug: "Costelinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "COWBCP",
              estoque: 0.64,
              estoque_minimo: 0.0,
              id: "706381781",
              marca: "Cara Preta",
              nome: "COWBOY CARA PRETA",
              slug: "Cowboy",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "COXINGAT",
              estoque: 16,
              estoque_minimo: 6.0,
              id: "623449932",
              marca: "Jerônimos",
              nome: "COXINHA DA ASA",
              slug: "Coxinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "DENVCP",
              estoque: 3.9,
              estoque_minimo: 2.0,
              id: "623449946",
              marca: "Cara Preta",
              nome: "DENVER CARA PRETA",
              slug: "Denver",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDMINE",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "794828451",
              marca: "Minerva",
              nome: "FRALDA MINERVA",
              slug: "Fralda",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDBG",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "773934587",
              marca: "Burg",
              nome: "FRALDÃO BURG",
              slug: "Falda",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRLDURUESTR",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "770209199",
              marca: "Ester de Lima",
              nome: "FRALDÃO URUGUAIO ESTER",
              slug: "Fralda",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDALI",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "778208038",
              marca: "Alimentar",
              nome: "FRALDINHA ALIMENTAR",
              slug: "Fraldinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDBASS",
              estoque: 0,
              estoque_minimo: 5.0,
              id: "791977192",
              marca: "Bassi",
              nome: "FRALDINHA BASSI",
              slug: "Fraldinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDCP",
              estoque: 0.86,
              estoque_minimo: 2.0,
              id: "663063892",
              marca: "Cara Preta",
              nome: "FRALDINHA CARA PRETA",
              slug: "Fraldinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDIEST92",
              estoque: 0,
              estoque_minimo: 5.0,
              id: "623449970",
              marca: "Estância 92",
              nome: "FRALDINHA ESTÂNCIA 92",
              slug: "Fraldinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDLS",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "744114547",
              marca: "Walls",
              nome: "FRALDINHA LS",
              slug: "Fraldinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDMTBOI",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "767806291",
              marca: "Mataboi",
              nome: "FRALDINHA MATABOI",
              slug: "Fraldinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDMNRVA",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "799895288",
              marca: "Minerva",
              nome: "FRALDINHA MINERVA",
              slug: "Fraldinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRALDMONTANA",
              estoque: 5.49,
              estoque_minimo: 4.0,
              id: "664322273",
              marca: "Montana Steakhouse",
              nome: "FRALDINHA MONTANA STEAKHOUSE",
              slug: "Fraldinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "FRDIRERARO",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "638432052",
              marca: "Raro",
              nome: "FRALDINHA RED RARO",
              slug: "Fraldinha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "HAMBCP",
              estoque: 5,
              estoque_minimo: 2.0,
              id: "623449997",
              marca: "Cara Preta",
              nome: "HAMBURGUER CARA PRETA",
              slug: "Hamburguer",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "HBRGTILP",
              estoque: 16,
              estoque_minimo: 0.0,
              id: "789712012",
              marca: "",
              nome: "HAMBURGUER DE TILÁPIA",
              slug: "Hamburguer",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "KAFTCHED",
              estoque: 5,
              estoque_minimo: 4.0,
              id: "623450013",
              marca: "Espetinhos Diferentes",
              nome: "KAFTA CHEDDAR",
              slug: "Kafta",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "LINGPERPRC",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "649329268",
              marca: "Porcão",
              nome: "LINGUIÇA  DE PERNIL PORCÃO",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGARTTLP",
              estoque: 14.5,
              estoque_minimo: 0.0,
              id: "785293008",
              marca: "",
              nome: "LINGUIÇA ARTESANAL DE TILÁPIA",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGBRAZBAC",
              estoque: 3,
              estoque_minimo: 3.0,
              id: "623450189",
              marca: "Brazas",
              nome: "LINGUIÇA CASEIRA BRAZAS BACON",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGBRZBQA",
              estoque: 0,
              estoque_minimo: 10.0,
              id: "623450199",
              marca: "Brazas",
              nome: "LINGUIÇA CASEIRA BRAZAS BACON, QUEIJO E ALHO PORÓ",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGBRZSFRG",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "800868965",
              marca: "Brazas",
              nome: "LINGUIÇA CASEIRA BRAZAS FRANGO",
              slug: "Linguiça",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "LINGBRAZPIM",
              estoque: 2.5,
              estoque_minimo: 3.0,
              id: "623450046",
              marca: "Brazas",
              nome: "LINGUIÇA CASEIRA BRAZAS PIMENTA",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGBRAZPIMBIQ",
              estoque: 3,
              estoque_minimo: 3.0,
              id: "623450182",
              marca: "Brazas",
              nome: "LINGUIÇA CASEIRA BRAZAS PIMENTA BIQUINHO",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGBRAZPRVL",
              estoque: 3.5,
              estoque_minimo: 3.0,
              id: "623450205",
              marca: "Brazas",
              nome: "LINGUIÇA CASEIRA BRAZAS PROVOLONE",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGBRAZTRAD",
              estoque: 4,
              estoque_minimo: 3.0,
              id: "623450210",
              marca: "Brazas",
              nome: "LINGUIÇA CASEIRA BRAZAS TRADICIONAL",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGCUIABO",
              estoque: 0,
              estoque_minimo: 2.0,
              id: "623450220",
              marca: "Boníssima",
              nome: "LINGUIÇA CUIABANA",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGCORDARG",
              estoque: 0,
              estoque_minimo: 4.0,
              id: "682500784",
              marca: "ARG",
              nome: "LINGUIÇA DE CORDEIRO ARG",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGCOSCP",
              estoque: 8.1,
              estoque_minimo: 6.0,
              id: "623450215",
              marca: "Cara Preta",
              nome: "LINGUIÇA DE COSTELA CARA PRETA",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "LINGPERNGARA",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "804981063",
              marca: "",
              nome: "LINGUIÇA DE PERNIL GARAPA",
              slug: "Linguiça",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "MAMIMINE",
              estoque: {
                codigo: "MAMIMINE",
                depositos: [
                  {
                    deposito: {
                      desconsiderar: "N",
                      empresa: "Brazas",
                      nome: "Geral",
                      saldo: 1.41,
                    },
                  },
                ],
                id: "794827835",
                nome: "MAMINHA MINERVA",
                saldo: 1.41,
                unidade: "kg",
                disponivel: false,
              },
              estoque_minimo: 0.0,
              id: "794827835",
              marca: "Minerva",
              nome: "MAMINHA MINERVA",
              slug: "Maminha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "MAMSTKPORC",
              estoque: 0,
              estoque_minimo: 4.0,
              id: "653960156",
              marca: "",
              nome: "MAMINHA STEAK MARINADO",
              slug: "Maminha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "MANTSUINCHED",
              estoque: 0,
              estoque_minimo: 2.0,
              id: "634824164",
              marca: "Boníssima",
              nome: "MANTA SUÍNA BACON E CHEDDAR",
              slug: "Manta Suína",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "MANTSUINQC",
              estoque: 2.5,
              estoque_minimo: 4.0,
              id: "623450225",
              marca: "Boníssima",
              nome: "MANTA SUÍNA QUEIJO COALHO",
              slug: "Manta Suína",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "MEDBATCHED",
              estoque: 3,
              estoque_minimo: 5.0,
              id: "623450236",
              marca: "Espetinhos Diferentes",
              nome: "MEDALHÃO DE BATATA COM CHEDDAR",
              slug: "Medalhão",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "MEDSURB",
              estoque: 0,
              estoque_minimo: 3.0,
              id: "628882233",
              marca: "Recheados Brasil",
              nome: "MEDALHÃO SUINO",
              slug: "Medalhão",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "PDFDNBT",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "804677691",
              marca: "",
              nome: "PÃO DE FRANGO COM REQUEIJAO",
              slug: "Pão de frango",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "PICAALIM",
              estoque: 0,
              estoque_minimo: 5.0,
              id: "786903341",
              marca: "Alimentar",
              nome: "PICANHA ALIMENTAR",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICANBLKAMI",
              estoque: 0,
              estoque_minimo: 2.0,
              id: "638379143",
              marca: "Angus",
              nome: "PICANHA ANA PAULA BLACK ANGUS",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICARREB",
              estoque: 0,
              estoque_minimo: 1.0,
              id: "623450327",
              marca: "Arrebeef",
              nome: "PICANHA ARREBEEF",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICARRBA",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "766299129",
              marca: "Arroba",
              nome: "PICANHA ARROBA",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICBASSI",
              estoque: 7.26,
              estoque_minimo: 3.0,
              id: "623450340",
              marca: "Bassi",
              nome: "PICANHA BASSI",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICBRAZ",
              estoque: 8.84,
              estoque_minimo: 7.0,
              id: "630551037",
              marca: "Brazas",
              nome: "PICANHA BRAZAS",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICCP",
              estoque: 7.82,
              estoque_minimo: 2.0,
              id: "623450354",
              marca: "Cara Preta",
              nome: "PICANHA CARA PRETA",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICCONCARSA",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "737002822",
              marca: "Concarsa",
              nome: "PICANHA CONCARSA",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICCRSUL",
              estoque: 10.38,
              estoque_minimo: 0.0,
              id: "774269426",
              marca: "Cruzeiro do Sul",
              nome: "PICANHA CRUZEIRO DO SUL",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICADIPRI",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "623450374",
              marca: "Di Prima",
              nome: "PICANHA DI PRIMA",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICFINEXIMP",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "733415440",
              marca: "Finexcor",
              nome: "PICANHA FINEXCOR",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICFRIGOIMP",
              estoque: 0,
              estoque_minimo: 2.0,
              id: "637005194",
              marca: "Frigochaco",
              nome: "PICANHA FRIGOCHACO",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICAFRIGO",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "795400098",
              marca: "Frigomerc",
              nome: "PICANHA FRIGOMERC",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICFRPA",
              estoque: 1.33,
              estoque_minimo: 0.0,
              id: "777807737",
              marca: "Fripai",
              nome: "PICANHA FRIPAI",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICAGORI",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "626302922",
              marca: "Gorina",
              nome: "PICANHA GORINA",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICGUARANI",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "723855204",
              marca: "Guarani",
              nome: "PICANHA GUARANI",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICAMATBOI",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "623450496",
              marca: "Mataboi",
              nome: "PICANHA MATABOI",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICAMINE",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "794829708",
              marca: "Minerva",
              nome: "PICANHA MINERVA",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICPARAG",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "801868011",
              marca: "Paraguaia",
              nome: "PICANHA PARAGUAIA",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICPUB",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "768983512",
              marca: "Pul B",
              nome: "PICANHA PUL B",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICAPULLA",
              estoque: 0,
              estoque_minimo: 10.0,
              id: "623450527",
              marca: "Pull A",
              nome: "PICANHA PULL A",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICSTGIU",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "797788298",
              marca: "Santa Giulia",
              nome: "PICANHA SANTA GIULIA",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICSUIALI",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "778208806",
              marca: "Alimentar",
              nome: "PICANHA SUINA ALIMENTAR",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICSUICIAC",
              estoque: 2.94,
              estoque_minimo: 0.0,
              id: "623450540",
              marca: "Cia Carne",
              nome: "PICANHA SUÍNA CIA CARNE",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICSUIMEL",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "643787433",
              marca: "Mellore",
              nome: "PICANHA SUINA MELLORE",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICSUISDL",
              estoque: 15.74,
              estoque_minimo: 0.0,
              id: "769851535",
              marca: "Saudali",
              nome: "PICANHA SUÍNA SAUDALI",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICSUISCHR",
              estoque: 0,
              estoque_minimo: 5.0,
              id: "623450553",
              marca: "Schroeder",
              nome: "PICANHA SUÍNA SCHROEDER",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICSTEMP",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "777808809",
              marca: "Temperatta",
              nome: "PICANHA SUÍNA TEMPERATA",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PICTACUA",
              estoque: 1.14,
              estoque_minimo: 3.0,
              id: "623450568",
              marca: "Tacuarembó",
              nome: "PICANHA TACUAREMBÓ",
              slug: "Picanha",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PCLMINRBBBQ",
              estoque: 0,
              estoque_minimo: 4.0,
              id: "687343884",
              marca: "",
              nome: "PICOLÉ MINEIRO BBQ",
              slug: "Picolé Mineiro",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "PCLMINRBEF",
              estoque: 12,
              estoque_minimo: 4.0,
              id: "687345363",
              marca: "",
              nome: "PICOLÉ MINEIRO ERVAS FINAS",
              slug: "Picolé Mineiro",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "PORCHRB",
              estoque: 4,
              estoque_minimo: 2.0,
              id: "623450585",
              marca: "Recheados Brasil",
              nome: "PORCHETTA",
              slug: "Porchetta",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PORTHOUSCP",
              estoque: 5.91,
              estoque_minimo: 2.0,
              id: "687338443",
              marca: "Cara Preta",
              nome: "PORTERHOUSE CARA PRETA",
              slug: "Porterhouse",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "PRMRIBRARO",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "647280665",
              marca: "Raro",
              nome: "PRIME RIB RARO",
              slug: "Prime Rib",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "SALSIGAT",
              estoque: 9,
              estoque_minimo: 3.0,
              id: "623450611",
              marca: "Jerônimos",
              nome: "SALSICHÃO",
              slug: "Salsichão",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "SALSIQUESCHR",
              estoque: 1,
              estoque_minimo: 10.0,
              id: "623450624",
              marca: "Schroeder",
              nome: "SALSICHÃO COM QUEIJO",
              slug: "Salsichão",
              unidade: "un",
              disponivel: false,
            },
            {
              codigo: "SHRTARG",
              estoque: 0,
              estoque_minimo: 5.0,
              id: "623450740",
              marca: "ARG",
              nome: "SHORT RIB ARG",
              slug: "Short Rib",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "SHRTCP",
              estoque: 0,
              estoque_minimo: 3.0,
              id: "623450753",
              marca: "Cara Preta",
              nome: "SHORT RIB CARA PRETA",
              slug: "Short Rib",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "SHRTRIBRARO",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "640758281",
              marca: "Raro",
              nome: "SHORT RIB RARO",
              slug: "Short Rib",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "SOBREGAT",
              estoque: 9,
              estoque_minimo: 12.0,
              id: "623450765",
              marca: "Jerônimos",
              nome: "SOBRECOXA DESOSSADA NA CERVEJA",
              slug: "Sobrecoxa Desossada",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "SOBRPRC",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "626670053",
              marca: "Porcão",
              nome: "SOBRECOXA DESOSSADA PORCÃO",
              slug: "Sobrecoxa Desossada",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "STKLOMBDIA",
              estoque: 0,
              estoque_minimo: 2.0,
              id: "692082492",
              marca: "",
              nome: "STEAK DE LOMBO",
              slug: "Steak",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "TBONECP",
              estoque: 2.22,
              estoque_minimo: 2.0,
              id: "623585662",
              marca: "Cara Preta",
              nome: "T-BONE CARA PRETA",
              slug: "T-Bone",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "TBONMINE",
              estoque: 0,
              estoque_minimo: 5.0,
              id: "638867885",
              marca: "Angus",
              nome: "T-BONE MINERVA ANGUS",
              slug: "T-Bone",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "TBNERARO",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "640758272",
              marca: "Raro",
              nome: "T-BONE RARO",
              slug: "T-Bone",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "TOMARARO",
              estoque: 0,
              estoque_minimo: 0.0,
              id: "647280670",
              marca: "Raro",
              nome: "TOMAHAWK RARO",
              slug: "Tomahawk",
              unidade: "kg",
              disponivel: false,
            },
            {
              codigo: "TLPA",
              estoque: 14,
              estoque_minimo: 0.0,
              id: "769175229",
              marca: "Jerônimos",
              nome: "TULIPA",
              slug: "Tulipa",
              unidade: "un",
              disponivel: false,
            },
          ];

          this.produtos.forEach((item) => {
            if(item.estoque < item.estoque_minimo){
              item.situacao = "Abaixo do estoque"
            } else if(item.estoque > item.estoque_minimo){
              item.situacao = `Acima do estoque em ${parseFloat(item.estoque - item.estoque_minimo).toFixed(2)} ${item.unidade}`
            } else {
              item.situacao = "Neutro"
            }
            this.slug.unshift(item.slug)
            this.fornecedores.unshift(item.marca)
          })

          this.fornecedores = this.fornecedores.reverse();
          this.slug = this.slug.reverse();

          if (this.loading !== "error") {
            setTimeout(() => {
              this.loading = "undefined";
            }, 4500);
          }
          this.barra = false;
        })
        .catch((error) => {
          this.loading = "error";
          this.errorMessage = error;
          console.error("There was an error!", error);
          this.barra = false;
        });
    },
  },
});
</script>
<style>
.card {
  padding: 20px 50px 20px 50px;
}
</style>
